version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - monity-network

  frontend:
    build:
      context: ./frontend/Monity
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./frontend/Monity:/app
      - /app/node_modules
    networks:
      - monity-network
    depends_on:
      - backend

networks:
  monity-network:
    driver: bridge
